[package]
name = "yprenees"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gumdrop = "0.8.1"
gumdrop_derive = "0.8.1"
image = "0.24.6"
imageproc = "0.23.0"
rusttype = "0.9.3"
